plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.1'
}

group = 'tech.purelove'
version = '2.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://nexus.scarsz.me/content/groups/public/' }
}

dependencies {
    implementation("net.dv8tion:JDA:5.0.0-beta.24")
    compileOnly 'org.spigotmc:spigot-api:1.21.11-R0.1-SNAPSHOT'
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(21)
}

processResources {
    inputs.property 'version', version
    filesMatching('plugin.yml') {
        expand version: version
    }
}

if (file("dev.gradle").exists()) {
    apply from: "dev.gradle"
}
